version: '2'
services:
  web:
    build: ./client
    volumes:
      - ./client/src:/code/src
    environment:
      - ENV=DEV
  api:
    build: ./server
    volumes:
      - ./server:/code
      - uwsgi-socket:/var/run/adventurelookup
    links:
      - db
      - redis
    environment:
      - ENV=DEV
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf.dev.d:/etc/nginx/conf.d
      - uwsgi-socket:/var/run/adventurelookup
    links:
      - web
    ports:
      - "80:80"
    environment:
      - ENV=DEV
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - ENV=DEV
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adventurelookup
  redis:
    image: redis

volumes:
  uwsgi-socket:
