# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('published', models.DateField()),
                ('min_level', models.IntegerField(help_text='The minumum character level for the adventure')),
                ('max_level', models.IntegerField(help_text='The maximum character level for the adventure')),
                ('min_characters', models.IntegerField(help_text='The minumum number of charactersfor the adventure')),
                ('max_characters', models.IntegerField(help_text='The maximum number of charactersfor the adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='authors',
            field=models.ManyToManyField(to='adventures.Author'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Publisher'),
        ),
    ]
