# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adventures.Publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Edition'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='setting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adventures.Setting'),
            preserve_default=False,
        ),
    ]
