# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_auto_20160909_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='setting',
        ),
        migrations.DeleteModel(
            name='Adventure',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
